FROM node:18-alpine

# Install some depenendencies
COPY package*.json ./
RUN npm install
COPY ./ ./

# TypeScript to JavaScript
RUN npm run tsc

#container network port number
EXPOSE 4001

# Default command
# CMD ["npm", "start"]
CMD ["npm", "run", "start"] 